apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-deudas.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-deudas.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api-deudas.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "api-deudas.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/deudas/health
              port: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /v1/deudas/health
              port: {{ .Values.service.targetPort }}
          env:
            - name: NODE_ENV
              value: {{ .Values.enviroment  }}
            - name: PORT
              value: "{{ .Values.service.targetPort }}"
            - name: HOSTNAME
              value: localhost
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-deudas.secrets" . }}
                  key: api-key
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-deudas.secrets" . }}
                  key: mongo
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-deudas.secrets" . }}
                  key: base-url
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-deudas.secrets" . }}
                  key: api-url
            - name: FLOW_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-deudas.secrets" . }}
                  key: flow-api-key
            - name: FLOW_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-deudas.secrets" . }}
                  key: flow-secret-key
            - name: FLOW_HOSTING
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-deudas.secrets" . }}
                  key: flow-hosting
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
