{{- $apiKey := .Values.secrets.apiKey | default (randAlphaNum 32) | b64enc  }}
{{- $mongo :=  .Values.secrets.mongoUrl | b64enc -}}
{{- $baseUrl := .Values.secrets.baseUrl | default (randAlphaNum 32) | b64enc  }}
{{- $apiUrl := .Values.secrets.apiUrl | default (randAlphaNum 32) | b64enc  }}
{{- $flowApiKey := .Values.secrets.flowApiKey | default (randAlphaNum 32) | b64enc  }}
{{- $flowSecretKey := .Values.secrets.flowSecretKey | default (randAlphaNum 32) | b64enc  }}
{{- $flowHosting := .Values.secrets.flowHosting | default (randAlphaNum 32) | b64enc  }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "api-hra-secrets") }}
{{- if $secret }}
{{- $apiKey = index $secret.data "api-key" }}
{{- $mongo = index $secret.data "mongo"}}
{{- $baseUrl = index $secret.data "api-key" }}
{{- $apiUrl = index $secret.data "api-key" }}
{{- $flowApiKey = index $secret.data "api-key" }}
{{- $flowSecretKey = index $secret.data "api-key" }}
{{- $flowHosting = index $secret.data "api-key" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ (include "api-deudas.fullname" .) | printf "%s-secrets" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-deudas.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ $apiKey }}
  mongo: {{ $mongo }}
  base-url: {{ $baseUrl }}
  api-url: {{ $apiUrl }}
  flow-api-key: {{ $flowApiKey }}
  flow-secret-key: {{ $flowSecretKey }}
  flow-hosting: {{ $flowHosting }}
